disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - implicit_getter
  - unused_optional_binding
force_cast: warning
trailing_semicolon: error
unneeded_break_in_switch: error
colon: error
weak_delegate: error
class_delegate_protocol: error
syntactic_sugar: error
