# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
os: osx
osx_image: xcode7.2
before_install:
- export LANG=en_US.UTF-8
- gem install cocoapods -v '~>0.39.0' # Since Travis is not always on latest version
- brew update
- brew install clang-format
- brew install python
- sudo pip install lizard
- pod install --project-directory=Example
script:
- xctool test -workspace Example/SkyKit.xcworkspace -scheme SKYKit-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint
- ./clang-check.sh
- lizard Pod/ -C 15 -w -i 0
notifications:
  slack:
    secure: "LTwnWl2i8c35uXkNv2QpKzesJajzvm2vAkmtLX1DKiSPGx93KRXRUIpafmotpFlST+J9Xzs7IWSEJguo8A42GX+chteBgOzsqnEwMccKgKvlIcCoH6mkAIh37mEdvT3NJYG1bg0OZ7cxntHRIeSJEUxHMuFinIT+LhPJbH+Bu7SbluQDlDEcE8ySuBpJiYq4KCEXT9fLuw+5eq55dQ21VniRd8kTWD4KPELkrRbU4/yAlixeA1mLDxuxGoOOQOp4McQOa3DjvGMqQqWoHM0PJeuUmdPkXFDmxUAUa9nN2nOY0fingsCI80Kuw6OyxP9Z9UWg4RBkncLTlw3gzAbxPk/kXIKLHyJpiyQiczFwREg07hBmvrGa//RuYeRPwc4mVKjxPd/4oq3KQq/BQzmS8H2934J7KYR9CTgBkUH6zjd59va4zxLY9icSWM/LMdJCA4QLs14gyo3ih9UJuKSbk8LUgwAIHI3775vIfMMBttuSjhIz3j0o5J8MOhxZaUZCBzCHBrTsRwKrOgNi+Pi1W8AvBKQAm7uspif45fna/XChbBuEnCxYgYNXwiBKYiZPxWn+cB5DOvmqVDXmI564rC4ZDaUK52NeGJ5F1llDWn8Eba/BcD8EgGU0B0Q2dvZgVu1GraqUu4ZX4OYTrnHVtov5n0M1+0cb7J0WeU1eUb4="
